userspace-module/utils/crypt-utils/crypt-utils.c File Reference
Implementation file for cryptographic utility functions.
#include "crypt-utils.h"
Macros
#define BLOCKSIZE 1024
This defines the max size of a block that can be cyphered. This definition is marked as internal and should not be used directly by the user.
#define IV_SIZE 32
The fixed size of the initialization vector IV . This definition is marked as internal and should not be used directly by the user.
#define KEY_SIZE 32
The fixed size of the key. This definition is marked as internal and should not be used directly by the user.
Functions
int do_crypt (FILE *in, FILE *out, int action, unsigned char *key_str)
High level function interface for performing AES encryption on FILE pointers Uses OpenSSL libcrypto EVP API
.
int check_entropy (void)
Verify if there is enough entropy in the system to generate a key.
void add_entropy (void)
Force new entropy in /dev/urandom.
void generate_key (unsigned char *destination)
Generate a new AES 256 key for a file.
unsigned char * encrypt_string (unsigned char *plaintext, const char *key, int *encrypted_key_len)
Encrypt the *plaintext string using a AES 256 key.
unsigned char * decrypt_string (unsigned char *ciphertext, const char *key)
Decrypt the *ciphertext string using a AES 256 key.
int is_valid_key (const unsigned char *key)
Check if a given key is valid.
const char * encrypt_file_name_with_hex (const char *file, const char *key)
const char * decrypt_file_name_with_hex (const char *enc_file, const char *key)
const char * encrypt_path (const char *path, const char *key)
Encrypts each part of the given path using a specified key.
const char * encrypt_path_and_filename (const char *path, const char *key)
Encrypts the given filename with its path using a specified key.
const char * decrypt_path (const char *encrypted_path, const char *key)
Decrypts each part of the given encrypted path using a specified key.
const char * decrypt_path_and_filename (const char *encrypted_path, const char *key)
Decrypts the given encrypted filename with its path using a specified key.
Detailed Description
Implementation file for cryptographic utility functions.
This file contains the implementation of various cryptographic utility functions, including AES encryption and decryption, key generation, entropy checks, and path encryption/decryption.
Author
By Carlo Alberto Giordnano
Created 18/10/23 by [Carlo Alberto Giordano]
Definition in file crypt-utils.c.
Macro Definition Documentation
BLOCKSIZE
#define BLOCKSIZE 1024
This defines the max size of a block that can be cyphered. This definition is marked as internal and should not be used directly by the user.
Definition at line 21 of file crypt-utils.c.
IV_SIZE
#define IV_SIZE 32
The fixed size of the initialization vector IV . This definition is marked as internal and should not be used directly by the user.
Definition at line 28 of file crypt-utils.c.
KEY_SIZE
#define KEY_SIZE 32
The fixed size of the key. This definition is marked as internal and should not be used directly by the user.
Definition at line 34 of file crypt-utils.c.
Function Documentation
add_entropy()
void add_entropy (void)
Force new entropy in /dev/urandom.
Returns
void
Note
Very dangerous, if this fails an error will be printed and the program will exit with EXIT_FAILURE
Definition at line 202 of file crypt-utils.c.
Referenced by generate_key().
check_entropy()
int check_entropy (void)
Verify if there is enough entropy in the system to generate a key.
Returns
A value greater than 0 corresponding to the entropy level, if an error occurs false is returned
Note
This function evaluates the entropy by checking the /proc/sys/kernel/random/entropy_avail file.
See also
man page 4 for random
Definition at line 174 of file crypt-utils.c.
Referenced by generate_key().
decrypt_file_name_with_hex()
const char * decrypt_file_name_with_hex (const char * enc_file, const char * key)
Definition at line 406 of file crypt-utils.c.
References decrypt_string(), and hex_to_string().
Referenced by decrypt_path(), decrypt_path_and_filename(), and tcfs_readdir().
decrypt_path()
const char * decrypt_path (const char * encrypted_path, const char * key)
Decrypts each part of the given encrypted path using a specified key.
Parameters
encrypted_path The input encrypted path to be decrypted.
key The decryption key.
Returns
A dynamically allocated string containing the decrypted path. It is the responsibility of the caller to free this memory.
Definition at line 645 of file crypt-utils.c.
References decrypt_file_name_with_hex(), and logMessage().
Referenced by tcfs_readdir().
decrypt_path_and_filename()
const char * decrypt_path_and_filename (const char * encrypted_path, const char * key)
Decrypts the given encrypted filename with its path using a specified key.
Parameters
encrypted_path The input encrypted path to be decrypted.
key The decryption key.
Returns
A dynamically allocated string containing the decrypted path with the decrypted filename. It is the responsibility of the caller to free this memory.
Definition at line 759 of file crypt-utils.c.
References decrypt_file_name_with_hex(), and logMessage().
decrypt_string()
unsigned char * decrypt_string (unsigned char * ciphertext, const char * key)
Decrypt the *ciphertext string using a AES 256 key.
Parameters
ciphertext This is the string to decrypt in HEX format
key The AES 256 KEY
Returns
unsigned char * The plaintext string will be allocated and then returned
Note
After the use remember to free the result
Definition at line 330 of file crypt-utils.c.
References logMessage().
Referenced by decrypt_file_name_with_hex(), tcfs_read(), and tcfs_write().
do_crypt()
int do_crypt (FILE * in, FILE * out, int action, unsigned char * key_str) [extern]
High level function interface for performing AES encryption on FILE pointers Uses OpenSSL libcrypto EVP API
.
Author
By Andy Sayler (www.andysayler.com)
 Created 04/17/12
Modified 18/10/23 by [Carlo Alberto Giordano]
Derived from OpenSSL.org EVP_Encrypt_* Manpage Examples
  http://www.openssl.org/docs/crypto/EVP_EncryptInit.html#EXAMPLES
 With additional information from Saju Pillai's OpenSSL AES Example
  http://saju.net.in/blog/?p=36
  http://saju.net.in/code/misc/openssl_aes.c.txt
Parameters
in The input file
out The output file
action Defines if the action to do on the input file should be of encryption or decryption.
See also
ENCRYPT
DECRYPT
Parameters
key_str The key that must be AES 256
Returns
1 if successful, 0 otherwise. An error might be printen by print_err() function,
See also
print_err
Note
This function cyphers using AES 256 CBC
Definition at line 63 of file crypt-utils.c.
References BLOCKSIZE, IV_SIZE, and KEY_SIZE.
Referenced by tcfs_read(), and tcfs_write().
encrypt_file_name_with_hex()
const char * encrypt_file_name_with_hex (const char * file, const char * key)
Definition at line 398 of file crypt-utils.c.
References encrypt_string(), and string_to_hex().
Referenced by encrypt_path(), and encrypt_path_and_filename().
encrypt_path()
const char * encrypt_path (const char * path, const char * key)
Encrypts each part of the given path using a specified key.
Parameters
path The input path to be encrypted.
key The encryption key.
Returns
A dynamically allocated string containing the encrypted path. It is the responsibility of the caller to free this memory.
Definition at line 420 of file crypt-utils.c.
References encrypt_file_name_with_hex(), and logMessage().
Referenced by tcfs_access(), tcfs_chmod(), tcfs_chown(), tcfs_getattr(), tcfs_mkdir(), tcfs_mknod(), tcfs_open(), tcfs_opendir(), tcfs_read(), tcfs_readdir(), tcfs_readlink(), tcfs_rmdir(), tcfs_setxattr(), tcfs_truncate(), tcfs_unlink(), tcfs_utimens(), and tcfs_write().
encrypt_path_and_filename()
const char * encrypt_path_and_filename (const char * path, const char * key)
Encrypts the given filename with its path using a specified key.
Parameters
path The input path to be encrypted.
key The encryption key.
Returns
A dynamically allocated string containing the encrypted path with the encrypted filename. It is the responsibility of the caller to free this memory.
Definition at line 532 of file crypt-utils.c.
References encrypt_file_name_with_hex(), and logMessage().
Referenced by tcfs_create(), tcfs_fsync(), tcfs_getxattr(), tcfs_link(), tcfs_listxattr(), tcfs_release(), tcfs_removexattr(), tcfs_rename(), and tcfs_symlink().
encrypt_string()
unsigned char * encrypt_string (unsigned char * plaintext, const char * key, int * encrypted_key_len)
Encrypt the *plaintext string using a AES 256 key.
Parameters
plaintext This is the string to encrypt
key The AES 256 KEY
encrypted_len This will be set to the encrypted string length
Returns
unsigned char * The encrypted string will be allocated and then returned
Note
After the use remember to free the result
Definition at line 278 of file crypt-utils.c.
Referenced by encrypt_file_name_with_hex(), and tcfs_create().
generate_key()
void generate_key (unsigned char * destination)
Generate a new AES 256 key for a file.
Parameters
destination Pointer to the string in which the generated key will be saved. If an error occurs it will be set to NULL
Returns
void
Definition at line 235 of file crypt-utils.c.
References add_entropy(), check_entropy(), is_valid_key(), logMessage(), and print_aes_key().
Referenced by tcfs_create().
is_valid_key()
int is_valid_key (const unsigned char * key)
Check if a given key is valid.
Parameters
key The key to validate
Returns
1 if successful, 0 otherwise. An error might be printen by print_err() function,
See also
print_err
Note
This function only checks for key length
Definition at line 388 of file crypt-utils.c.
Referenced by generate_key(), main(), and tcfs_create().