daemon/daemon_utils/common_utils/print/print_utils.c File Reference
This file defines some QoL functions.
#include "print_utils.h"
Functions
void print_err (const char *format,...)
Format and print data as an error.
void print_msg (const char *format,...)
Format and print data as a message.
void print_warn (const char *format,...)
Format and print data as a waring.
void print_debug (const char *format,...)
Format and print data as a debug.
Variables
int cleared = 0
If it is 0 the log file will be cleared, if is 1 the log file will we open as append.
Detailed Description
This file defines some QoL functions.
Definition in file print_utils.c.
Function Documentation
print_debug()
void print_debug (const char * format, ...)
Format and print data as a debug.
Parameters
format the string that will formatted and printed
... Print optional ARGUMENT(s) according to format
Returns
void
Note
Will also log using systemD
"DEBUG=" will be prepended to format
Definition at line 144 of file print_utils.c.
print_err()
void print_err (const char * format, ...)
Format and print data as an error.
Parameters
format the string that will formatted and printed
... Print optional ARGUMENT(s) according to format
Returns
void
Note
Will also log using systemD
"ERROR=" will be prepended to format
"Err_Numebr:d" will be appended to the formatted string describing the error number
after Err_Number "-> s" will be appended printing the std-error
Definition at line 78 of file print_utils.c.
Referenced by dequeue(), enqueue(), get_user_by_name(), get_user_by_pid(), handle_incoming_messages(), handle_outgoing_messages(), init_context(), init_queue(), insert(), main(), remove_by_pid(), and remove_by_user().
print_msg()
void print_msg (const char * format, ...)
Format and print data as a message.
Parameters
format the string that will formatted and printed
... Print optional ARGUMENT(s) according to format
Returns
void
Note
Will also log using systemD
"MESSAGE=" will be prepended to format
Definition at line 100 of file print_utils.c.
Referenced by dequeue(), disconnect_db(), enqueue(), get_user_by_name(), get_user_by_pid(), handle_incoming_messages(), handle_outgoing_messages(), handle_termination(), init_queue(), insert(), json_to_qm_user(), main(), print_all_keys(), register_user(), remove_by_pid(), struct_to_json(), and unregister_user().
print_warn()
void print_warn (const char * format, ...)
Format and print data as a waring.
Parameters
format the string that will formatted and printed
... Print optional ARGUMENT(s) according to format
Returns
void
Note
Will also log using systemD
"WARNING=" will be prepended to format
Definition at line 122 of file print_utils.c.
Variable Documentation
cleared
int cleared = 0
If it is 0 the log file will be cleared, if is 1 the log file will we open as append.
Definition at line 14 of file print_utils.c.