daemon/daemon_utils/common_utils/db/redis.c File Reference
All the function in this file should not be used directly, instead use the function defined by user_db.
#include "redis.h"
#include "../json/json_tools.h"
#include "../print/print_utils.h"
#include <hiredis/hiredis.h>
Macros
#define PORT 6380
The port of the redis DB.
Functions
void print_all_keys ()
For debugging only. Prints all the keys in the database.
int init_context ()
initialize the context for the Redis DB
void free_context ()
Free the hiredis context variable.
qm_user * json_to_qm_user (char *json)
Internal function to simplify the casting of a json to a qm_user struct.
qm_user * get_user_by_pid (pid_t pid)
Fetch the user on the DB with key pid.
qm_user * get_user_by_name (const char *name)
Fetch the user on the DB with key name.
int insert (qm_user *user)
Insert a new user in the DB.
int remove_by_pid (pid_t pid)
Remove a user from the DB using the PID as key.
int remove_by_user (char *name)
Remove a user from the DB using the name as key.
Variables
const char HOST [] = "127.0.0.1"
redisContext * context
Pointer to the context of Redis DB.
Detailed Description
All the function in this file should not be used directly, instead use the function defined by user_db.
This file is marked as internal and the corresponding header should not be used by the user. Please refer to the see section
See also
\ref user_db.c
Definition in file redis.c.
Macro Definition Documentation
PORT
#define PORT 6380
The port of the redis DB.
This definition is marked as internal and be used directly
Todo
Todo This should be passed as a parameter to the daemon
Definition at line 27 of file redis.c.
Function Documentation
free_context()
void free_context ()
Free the hiredis context variable.
This function is marked as internal and should not be used by the user
Returns
void
Definition at line 92 of file redis.c.
References context.
Referenced by disconnect_db().
get_user_by_name()
qm_user * get_user_by_name (const char * name)
Fetch the user on the DB with key name.
This function is marked as internal and should not be used by the user
Parameters
const char *name The key of the row
Returns
qm_user* A pointer to the allocated qm_user* struct
Definition at line 165 of file redis.c.
References context, json_to_qm_user(), qm_user::pid, print_err(), print_msg(), and qm_user::user.
Referenced by remove_by_user().
get_user_by_pid()
qm_user * get_user_by_pid (pid_t pid)
Fetch the user on the DB with key pid.
This function is marked as internal and should not be used by the user
Parameters
pid_t pid The key of the row
Returns
qm_user* A pointer to the allocated qm_user* struct
Definition at line 122 of file redis.c.
References context, json_to_qm_user(), qm_user::pid, print_err(), print_msg(), and qm_user::user.
Referenced by remove_by_pid().
init_context()
int init_context ()
initialize the context for the Redis DB
This function is marked as internal and should not be used by the user
Returns
1 if initialization was successful or the database was already initialized, 0 on failure
Definition at line 72 of file redis.c.
References context, PORT, and print_err().
Referenced by register_user().
insert()
int insert (qm_user * user)
Insert a new user in the DB.
This function is marked as internal and should not be used by the user
Parameters
qm_user* A pointer to the allocated qm_user* struct
Returns
1 if successful, 0 otherwise. An error might be printen by print_err() function,
See also
print_err
Note
The user will be set 2 times, once with key user->pid and once with key user->name
If an error is thrown it will be printed by print_err() function
Definition at line 211 of file redis.c.
References context, qm_user::pid, print_err(), print_msg(), and qm_user::user.
Referenced by register_user().
json_to_qm_user()
qm_user * json_to_qm_user (char * json)
Internal function to simplify the casting of a json to a qm_user struct.
This function is marked as internal and should not be used by the user
Parameters
char *json the json string representing the qm_user struct
Returns
qm_user* A pointer to the allocated qm_user* struct
Definition at line 104 of file redis.c.
References print_msg().
Referenced by get_user_by_name(), and get_user_by_pid().
print_all_keys()
void print_all_keys ()
For debugging only. Prints all the keys in the database.
This function is marked as internal and should not be used by the user
Returns
void
Definition at line 42 of file redis.c.
References context, and print_msg().
Referenced by register_user(), and unregister_user().
remove_by_pid()
int remove_by_pid (pid_t pid)
Remove a user from the DB using the PID as key.
This function is marked as internal and should not be used by the user
Parameters
pid_t pid The key
Returns
1 if successful, 0 otherwise. An error might be printen by print_err() function,
See also
print_err
Note
Will also remove the corresponding entry by name.
If an error is thrown it will be printed using the print_err() function
Definition at line 256 of file redis.c.
References context, get_user_by_pid(), print_err(), print_msg(), and qm_user::user.
Referenced by unregister_user().
remove_by_user()
int remove_by_user (char * name)
Remove a user from the DB using the name as key.
This function is marked as internal and should not be used by the user
Parameters
char *name The key
Returns
1 if successful, 0 otherwise. An error might be printen by print_err() function,
See also
print_err
Note
Will also remove the corresponding entry by PID
If an error is thrown it will be printed using the print_err() function
Definition at line 292 of file redis.c.
References context, get_user_by_name(), qm_user::pid, and print_err().
Variable Documentation
context
redisContext * context
Pointer to the context of Redis DB.
This variable is marked as internal and should not be used by the user
Definition at line 34 of file redis.c.
Referenced by free_context(), get_user_by_name(), get_user_by_pid(), init_context(), insert(), print_all_keys(), remove_by_pid(), and remove_by_user().
HOST
const char HOST[] = "127.0.0.1"
Definition at line 20 of file redis.c.