daemon/tcfs_daemon.c File Reference
This is the core of the daemon.
#include "daemon_utils/daemon_tools/tcfs_daemon_tools.h"
Functions
void handle_termination (int signum)
Handle the termination if SIGTERM is received.
int main ()
main function of the daemon. This will daemonize the program, spawn a thread to handle messages and handle unexpected termination of the thread
Variables
volatile int terminate = 0
If the spawned threads terminate abruptly they should set this to 1, so that the daemon can terminate.
pthread_mutex_t terminate_mutex = PTHREAD_MUTEX_INITIALIZER
Mutex needed to set the var terminate to 1 safely.
const char MQUEUE [] = "/tcfs_queue"
the queue file location
Detailed Description
This is the core of the daemon.
Note
Forking is disable at the moment, this meas it will run as a "normal" program
the main function spawns a thread to handle incoming messages on the queue
Todo
Todo : Enable forking
Run the daemon via SystemD
Definition in file tcfs_daemon.c.
Function Documentation
handle_termination()
void handle_termination (int signum)
Handle the termination if SIGTERM is received.
Parameters
signum Integer corresponding to SIGNUM
Todo
Todo : Implement remove_queue() to clear and delete the queue
Definition at line 40 of file tcfs_daemon.c.
References print_msg().
Referenced by main().
main()
int main ()
main function of the daemon. This will daemonize the program, spawn a thread to handle messages and handle unexpected termination of the thread
Todo
Todo : The brief description is basically false advertisement. It only spawn a thread and hangs infinitely
: Remove the thread that spawns handle_outgoing_messages. This must not make it into final release
Definition at line 56 of file tcfs_daemon.c.
References handle_incoming_messages(), handle_outgoing_messages(), handle_termination(), init_queue(), MQUEUE, print_err(), print_msg(), and terminate.
Variable Documentation
MQUEUE
MQUEUE = "/tcfs_queue"
the queue file location
Definition at line 32 of file tcfs_daemon.c.
Referenced by main().
terminate
volatile int terminate = 0
If the spawned threads terminate abruptly they should set this to 1, so that the daemon can terminate.
Todo
Todo : Implement logic to make this work
Definition at line 20 of file tcfs_daemon.c.
Referenced by main().
terminate_mutex
pthread_mutex_t terminate_mutex = PTHREAD_MUTEX_INITIALIZER
Mutex needed to set the var terminate to 1 safely.
Todo
Todo : implement logic to make this work
Definition at line 26 of file tcfs_daemon.c.