user/old_stuff/tcfs_helper_tools.c File Reference
This file contains the logic and implementation of functions needed to perform the operations requested in user_tcfs.c.
#include "tcfs_helper_tools.h"
Macros
#define PASS_SIZE 33
Set the password size to 33 as AES 256 uses a 32 byte key. An \0 is added for safety. This definition is marked as internal and should not be used directly by the user.
Functions
int handle_local_mount ()
int handle_remote_mount ()
int handle_folder_mount ()
int do_mount ()
Execute the mount of either a Network FS (for ex NFS), Local FS (for ex a block device), Local folder (a folder of the system)
int generate_random_string (char *str)
Generate a random string that will be used as a folder name for the mount. This function is marked as internal and should not be used by the user.
int directory_exists (const char *path)
Check if a directory already exists. This function is marked as internal and should not be used by the user.
char * setup_tcfs_mount_folder ()
Creates the .tcfs folder in the user HOME. Then this creates a folder with a random name so that create_tcfs_mount_local_folder function can use it. create_tcfs_mount_local_folder This function is marked as internal and should not be used by the user.
void get_pass (char *pw)
fetch the password of the current user. This function is marked as internal and should not be used by the user
void get_source_dest (char *source, char *dest)
char * create_tcfs_mount_local_folder ()
Create a temporary folder in HOME/.tcfs.
int mount_tcfs_folder (char *tmp_path, char *destination)
void clearKeyboardBuffer ()
int setup_tcfs_env ()
Detailed Description
This file contains the logic and implementation of functions needed to perform the operations requested in user_tcfs.c.
See also
user_tcfs.c
Definition in file tcfs_helper_tools.c.
Macro Definition Documentation
PASS_SIZE
#define PASS_SIZE 33
Set the password size to 33 as AES 256 uses a 32 byte key. An \0 is added for safety. This definition is marked as internal and should not be used directly by the user.
Definition at line 14 of file tcfs_helper_tools.c.
Function Documentation
clearKeyboardBuffer()
void clearKeyboardBuffer ()
Definition at line 339 of file tcfs_helper_tools.c.
Referenced by handle_remote_mount().
create_tcfs_mount_local_folder()
char * create_tcfs_mount_local_folder ()
Create a temporary folder in HOME/.tcfs.
Returns
char * the fullpath to the generated folder
Definition at line 219 of file tcfs_helper_tools.c.
References setup_tcfs_mount_folder().
Referenced by handle_local_mount().
directory_exists()
int directory_exists (const char * path)
Check if a directory already exists. This function is marked as internal and should not be used by the user.
Parameters
path Fullpath to the dir
Returns
int _ret
Definition at line 83 of file tcfs_helper_tools.c.
Referenced by setup_tcfs_mount_folder().
do_mount()
int do_mount ()
Execute the mount of either a Network FS (for ex NFS), Local FS (for ex a block device), Local folder (a folder of the system)
Returns
_ret
Definition at line 25 of file tcfs_helper_tools.c.
References handle_folder_mount(), handle_local_mount(), and handle_remote_mount().
Referenced by main().
generate_random_string()
int generate_random_string (char * str)
Generate a random string that will be used as a folder name for the mount. This function is marked as internal and should not be used by the user.
Parameters
str The result will be saved here
Returns
int _ret
Definition at line 64 of file tcfs_helper_tools.c.
Referenced by setup_tcfs_mount_folder().
get_pass()
void get_pass (char * pw)
fetch the password of the current user. This function is marked as internal and should not be used by the user
Parameters
pw String to save the password to
Todo
Todo This will be changed when a public/private key model will be avilable to TCFS userspace module
Definition at line 162 of file tcfs_helper_tools.c.
References PASS_SIZE.
Referenced by mount_tcfs_folder().
get_source_dest()
void get_source_dest (char * source, char * dest)
Parameters
Ask the user to insert the source and the destination of the mount. This function is marked as internal and should not be used by the user
Definition at line 204 of file tcfs_helper_tools.c.
Referenced by handle_folder_mount(), and handle_local_mount().
handle_folder_mount()
int handle_folder_mount ()
Definition at line 318 of file tcfs_helper_tools.c.
References get_source_dest(), and mount_tcfs_folder().
Referenced by do_mount().
handle_local_mount()
int handle_local_mount ()
Definition at line 274 of file tcfs_helper_tools.c.
References create_tcfs_mount_local_folder(), get_source_dest(), and mount_tcfs_folder().
Referenced by do_mount().
handle_remote_mount()
int handle_remote_mount ()
Definition at line 347 of file tcfs_helper_tools.c.
References clearKeyboardBuffer(), and mount_tcfs_folder().
Referenced by do_mount().
mount_tcfs_folder()
int mount_tcfs_folder (char * tmp_path, char * destination)
Definition at line 235 of file tcfs_helper_tools.c.
References get_pass(), and PASS_SIZE.
Referenced by handle_folder_mount(), handle_local_mount(), and handle_remote_mount().
setup_tcfs_env()
int setup_tcfs_env ()
Definition at line 405 of file tcfs_helper_tools.c.
Referenced by main().
setup_tcfs_mount_folder()
char * setup_tcfs_mount_folder ()
Creates the .tcfs folder in the user HOME. Then this creates a folder with a random name so that create_tcfs_mount_local_folder function can use it. create_tcfs_mount_local_folder This function is marked as internal and should not be used by the user.
Returns
a folder with a random name inside the $HOME/.tcfs folder
Definition at line 95 of file tcfs_helper_tools.c.
References directory_exists(), and generate_random_string().
Referenced by create_tcfs_mount_local_folder().