user/old_stuff/tcfs_helper_tools.h File Reference
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <termios.h>
#include <time.h>
#include <unistd.h>
Functions
int do_mount ()
Execute the mount of either a Network FS (for ex NFS), Local FS (for ex a block device), Local folder (a folder of the system)
int setup_tcfs_env ()
Function Documentation
do_mount()
int do_mount ()
Execute the mount of either a Network FS (for ex NFS), Local FS (for ex a block device), Local folder (a folder of the system)
Returns
_ret
Definition at line 25 of file tcfs_helper_tools.c.
References handle_folder_mount(), handle_local_mount(), and handle_remote_mount().
Referenced by main().
setup_tcfs_env()
int setup_tcfs_env ()
Definition at line 405 of file tcfs_helper_tools.c.
Referenced by main().