userspace-module/utils/tcfs_utils/tcfs_utils.c File Reference
This file contains an assortment of functions used by tcfs.c.
#include "tcfs_utils.h"
#include "../crypt-utils/crypt-utils.h"
Functions
void get_user_name (char *buf, size_t size)
Fetch the username of the current user.
int is_encrypted (const char *path)
Check if a file is encrypted by TCFS.
char * prefix_path (const char *path, const char *realpath)
Prefix the realpath to the fuse path.
int read_file (FILE *file)
Read a file, useful for debugging tmpfiles.
int get_encrypted_key (char *filepath, unsigned char *encrypted_key)
Get the xattr value describing the key of a file.
void print_aes_key (unsigned char *key)
Print the value of an AES key.
char * string_to_hex (const char *input)
Convert a string to its hexadecimal representation.
char * hex_to_string (const char *input)
Convert a hexadecimal string to its ASCII representation.
void logMessage (const char *format,...)
Logs a formatted message to a file with timestamp.
Detailed Description
This file contains an assortment of functions used by tcfs.c.
See also
tcfs.c
Definition in file tcfs_utils.c.
Function Documentation
get_encrypted_key()
int get_encrypted_key (char * filepath, unsigned char * encrypted_key)
Get the xattr value describing the key of a file.
Deprecated
Deprecated Currently has no use. Was once used for debugging.
Parameters
filepath The full path of the file.
encrypted_key The buffer to save the encrypted key to.
Returns
1 if successful, 0 otherwise. An error might be printen by print_err() function,
See also
print_err
Definition at line 123 of file tcfs_utils.c.
References is_encrypted(), and logMessage().
get_user_name()
void get_user_name (char * buf, size_t size)
Fetch the username of the current user.
Parameters
buf The buffer where the username will be written.
size The size of the buffer.
Returns
void
Note
If an error occurs, it will be printed, and the buffer will not be modified.
Definition at line 19 of file tcfs_utils.c.
Referenced by tcfs_read().
hex_to_string()
char * hex_to_string (const char * input)
Convert a hexadecimal string to its ASCII representation.
Parameters
input The input hexadecimal string.
Returns
char * The ASCII representation of the input hexadecimal string.
Note
Remember to free the result after use.
Definition at line 218 of file tcfs_utils.c.
References logMessage().
Referenced by decrypt_file_name_with_hex().
is_encrypted()
int is_encrypted (const char * path)
Check if a file is encrypted by TCFS.
Parameters
path The full path of the file.
Returns
1 if successful, 0 otherwise. An error might be printen by print_err() function,
See also
print_err
Definition at line 35 of file tcfs_utils.c.
Referenced by get_encrypted_key().
logMessage()
void logMessage (const char * format, ...)
Logs a formatted message to a file with timestamp.
This function logs a formatted message to a specified log file along with a timestamp. It accepts a variable number of parameters, similar to printf.
Parameters
format The format string for the log message.
... Additional parameters to be formatted into the log message.
Definition at line 262 of file tcfs_utils.c.
References DEBUG, and LOGFILE.
Referenced by decrypt_path(), decrypt_path_and_filename(), decrypt_string(), encrypt_path(), encrypt_path_and_filename(), generate_key(), get_encrypted_key(), hex_to_string(), main(), print_aes_key(), string_to_hex(), tcfs_access(), tcfs_chmod(), tcfs_chown(), tcfs_create(), tcfs_fsync(), tcfs_getattr(), tcfs_getxattr(), tcfs_link(), tcfs_listxattr(), tcfs_mkdir(), tcfs_mknod(), tcfs_open(), tcfs_opendir(), tcfs_read(), tcfs_readdir(), tcfs_readlink(), tcfs_release(), tcfs_removexattr(), tcfs_rename(), tcfs_rmdir(), tcfs_setxattr(), tcfs_statfs(), tcfs_symlink(), tcfs_truncate(), tcfs_unlink(), tcfs_utimens(), and tcfs_write().
prefix_path()
char * prefix_path (const char * path, const char * realpath)
Prefix the realpath to the fuse path.
Parameters
path The fuse path.
realpath The realpath to the directory mounted by TCFS.
Returns
char * An allocated string containing the full path to the file.
Note
Please free the result after use.
Definition at line 53 of file tcfs_utils.c.
Referenced by tcfs_access(), tcfs_chmod(), tcfs_chown(), tcfs_create(), tcfs_fsync(), tcfs_getattr(), tcfs_getxattr(), tcfs_link(), tcfs_listxattr(), tcfs_mkdir(), tcfs_mknod(), tcfs_open(), tcfs_opendir(), tcfs_read(), tcfs_readdir(), tcfs_readlink(), tcfs_release(), tcfs_removexattr(), tcfs_rename(), tcfs_rmdir(), tcfs_setxattr(), tcfs_statfs(), tcfs_symlink(), tcfs_truncate(), tcfs_unlink(), tcfs_utimens(), and tcfs_write().
print_aes_key()
void print_aes_key (unsigned char * key)
Print the value of an AES key.
Deprecated
Deprecated Currently has no use. Printing the AES key is considered excessive.
Warning
THIS WILL PRINT THE AES KEY TO STDOUT. TCFS trusts the user by design, but this is excessive.
Parameters
key The string containing the key.
Returns
void
Definition at line 165 of file tcfs_utils.c.
References logMessage().
Referenced by generate_key().
read_file()
int read_file (FILE * file)
Read a file, useful for debugging tmpfiles.
Deprecated
Deprecated Currently has no use.
Parameters
file The file to read.
Returns
true
Note
It will print "file was empty" if the file was empty.
Definition at line 95 of file tcfs_utils.c.
string_to_hex()
char * string_to_hex (const char * input)
Convert a string to its hexadecimal representation.
Parameters
input The input string.
Returns
char * The hexadecimal representation of the input string.
Note
Remember to free the result after use.
Definition at line 182 of file tcfs_utils.c.
References logMessage().
Referenced by encrypt_file_name_with_hex().