userspace-module/tcfs.c File Reference
#include "utils/crypt-utils/crypt-utils.h"
#include "utils/tcfs_utils/tcfs_utils.h"
#include <argp.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <fuse3/fuse.h>
#include <limits.h>
#include <linux/limits.h>
#include <pwd.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/xattr.h>
#include <time.h>
#include <unistd.h>
Classes
struct arguments
Structure to store command-line arguments.
Macros
#define FUSE_USE_VERSION 30
#define HAVE_SETXATTR
#define _XOPEN_SOURCE 500
#define TCFS_SUCCESS 0
#define ERR_inval_arg_len 1
#define ERR_inval_key 2
#define ERR_invalid_enc_dir_name 3
Functions
static int tcfs_getxattr (const char *fuse_path, const char *name, char *value, size_t size)
Get extended attribute data.
static int tcfs_opendir (const char *fuse_path, struct fuse_file_info *fi)
Opens a directory.
static int tcfs_getattr (const char *fuse_path, struct stat *stbuf, struct fuse_file_info *fi)
Gets file attributes.
static int tcfs_access (const char *fuse_path, int mask)
Checks file access permissions.
static int tcfs_readlink (const char *fuse_path, char *buf, size_t size)
Reads the target of a symbolic link.
static int tcfs_readdir (const char *fuse_path, void *buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fi, enum fuse_readdir_flags frdf)
Reads a directory.
static int tcfs_mknod (const char *fuse_path, mode_t mode, dev_t rdev)
Creates a regular file or a special file (block or character).
static int tcfs_mkdir (const char *fuse_path, mode_t mode)
Creates a directory.
static int tcfs_unlink (const char *fuse_path)
Removes a file.
static int tcfs_rmdir (const char *fuse_path)
Removes a directory.
static int tcfs_symlink (const char *from, const char *to)
Creates a symbolic link.
static int tcfs_rename (const char *from, const char *to, unsigned int flags)
Renames a file or a directory.
static int tcfs_link (const char *from, const char *to)
Creates a hard link.
static int tcfs_chmod (const char *fuse_path, mode_t mode, struct fuse_file_info *fi)
Changes the permissions of a file.
static int tcfs_chown (const char *fuse_path, uid_t uid, gid_t gid, struct fuse_file_info *fi)
Changes the owner and group of a file.
static int tcfs_truncate (const char *fuse_path, off_t size, struct fuse_file_info *fi)
Truncates or extends the size of a file.
static int tcfs_utimens (const char *fuse_path, const struct timespec ts[2], struct fuse_file_info *fi)
Modify the access and modification timestamps of a file in the TCFS file system.
static int tcfs_open (const char *fuse_path, struct fuse_file_info *fi)
Opens a file.
static int file_size (FILE *file)
Get the size of a file in the TCFS file system.
static int tcfs_read (const char *fuse_path, char *buf, size_t size, off_t offset, struct fuse_file_info *fi)
Reads data from an open file.
static int tcfs_write (const char *fuse_path, const char *buf, size_t size, off_t offset, struct fuse_file_info *fi)
Writes data to an open file.
static int tcfs_statfs (const char *fuse_path, struct statvfs *stbuf)
Get file system statistics.
static int tcfs_setxattr (const char *fuse_path, const char *name, const char *value, size_t size, int flags)
Sets extended attributes.
static int tcfs_create (const char *fuse_path, mode_t mode, struct fuse_file_info *fi)
Create and open a file.
static int tcfs_release (const char *fuse_path, struct fuse_file_info *fi)
Releases an open file.
static int tcfs_fsync (const char *fuse_path, int isdatasync, struct fuse_file_info *fi)
Synchronizes file contents.
static int tcfs_listxattr (const char *fuse_path, char *list, size_t size)
Lists extended attributes.
static int tcfs_removexattr (const char *fuse_path, const char *name)
Remove an extended attribute.
static error_t parse_opt (int key, char *arg, struct argp_state *state)
Parse command-line options.
int main (int argc, char *argv[])
Main entry point for TCFS.
Variables
char * root_path
Contains the fullpath to the mounted directory.
char * password
Contains the password passed to TCFS when started.
static struct fuse_operations tcfs_oper
TCFS file system operations.
const char * argp_program_version = "TCFS Alpha"
TCFS version information.
const char * argp_program_bug_address = "carloalbertogiordano@duck.com"
TCFS bug report email address.
static char doc []
Documentation string for TCFS.
static char args_doc [] = ""
Argument documentation string for TCFS.
static struct argp_option options []
TCFS command-line options.
static struct argp argp = { options, parse_opt, args_doc, doc, 0, NULL, NULL }
TCFS argp structure.
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 500
Definition at line 17 of file tcfs.c.
ERR_inval_arg_len
#define ERR_inval_arg_len 1
Definition at line 21 of file tcfs.c.
ERR_inval_key
#define ERR_inval_key 2
Definition at line 22 of file tcfs.c.
ERR_invalid_enc_dir_name
#define ERR_invalid_enc_dir_name 3
Definition at line 23 of file tcfs.c.
FUSE_USE_VERSION
#define FUSE_USE_VERSION 30
Definition at line 6 of file tcfs.c.
HAVE_SETXATTR
#define HAVE_SETXATTR
Definition at line 7 of file tcfs.c.
TCFS_SUCCESS
#define TCFS_SUCCESS 0
Definition at line 20 of file tcfs.c.
Function Documentation
file_size()
static int file_size (FILE * file) [inline], [static]
Get the size of a file in the TCFS file system.
This function is called when the getattr operation is performed on a file in the TCFS to obtain file attributes.
Parameters
fuse_path The path of the encrypted file for which the size is requested.
stbuf Buffer to store the file attributes, including the size.
fi File information structure provided by FUSE.
Returns
TCFS_SUCCESS on success, negative error code on failure.
The tcfs_file_size function is invoked to retrieve the size of a file within the TCFS. It decodes the encrypted file path, translates it into the actual file path on the underlying file system, and then uses the getattr function to obtain the file attributes, including the file size.
Parameters
fuse_path The path of the encrypted file within the TCFS.
stbuf Buffer to store the file attributes, including the file size.
fi File information provided by FUSE, which may be used to obtain additional details about the file if needed.
Returns
true on success. On failure, it returns a negative error code representing the type of error encountered.
Note
The function is a crucial part of file attribute retrieval, and the size is a fundamental attribute of a file.
The correct functioning of this function is essential for providing accurate information about the file size.
Warning
Ensure that the function correctly translates the encrypted file path into the actual file path on the underlying file system.
Verify that the file attributes, especially the size, are accurately retrieved and reported in the stbuf buffer.
Definition at line 711 of file tcfs.c.
Referenced by tcfs_read(), and tcfs_write().
main()
int main (int argc, char * argv[])
Main entry point for TCFS.
Parameters
argc Number of command-line arguments.
argv Array of command-line arguments.
Returns
0 on success, error code on failure.
Definition at line 1412 of file tcfs.c.
References arguments::destination, ERR_inval_arg_len, ERR_inval_key, is_valid_key(), logMessage(), password, arguments::password, root_path, arguments::source, tcfs_oper, and TCFS_SUCCESS.
parse_opt()
static error_t parse_opt (int key, char * arg, struct argp_state * state) [static]
Parse command-line options.
Parameters
key Option key.
arg Option argument.
state Parser state.
Returns
0 on success, error code on failure.
Definition at line 1374 of file tcfs.c.
References arguments::destination, arguments::password, arguments::source, and TCFS_SUCCESS.
tcfs_access()
static int tcfs_access (const char * fuse_path, int mask) [static]
Checks file access permissions.
This function is called to check file access permissions.
Parameters
fuse_path The path to the file/directory.
mask The requested access permissions.
Returns
true on success, a negative error code on failure.
Definition at line 132 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
Referenced by tcfs_write().
tcfs_chmod()
static int tcfs_chmod (const char * fuse_path, mode_t mode, struct fuse_file_info * fi) [static]
Changes the permissions of a file.
This function is called to change the permissions of a file.
Parameters
fuse_path The path to the file.
mode New file mode.
fi File information.
Returns
true on success, a negative error code on failure.
Definition at line 497 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_chown()
static int tcfs_chown (const char * fuse_path, uid_t uid, gid_t gid, struct fuse_file_info * fi) [static]
Changes the owner and group of a file.
This function is called to change the owner and group of a file.
Parameters
fuse_path The path to the file.
uid New user ID.
gid New group ID.
fi File information.
Returns
true on success, a negative error code on failure.
Definition at line 530 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_create()
static int tcfs_create (const char * fuse_path, mode_t mode, struct fuse_file_info * fi) [static]
Create and open a file.
This function is called when a new file is created in the TCFS file system.
Parameters
fuse_path The path of the file to be created.
mode The mode of the file (permissions).
fi File information, including flags and an open file handle.
Returns
TCFS_SUCCESS on success, negative error code on failure.
The create function is invoked when a new file is created in the TCFS file system. It is responsible for setting up the necessary data structures, allocating resources, and opening the file for subsequent read and write operations.
Parameters
fuse_path The path of the file within the TCFS.
mode The mode of the file, specifying permissions and other attributes.
fi File information containing flags and an open file handle.
Returns
true on success. On failure, it returns a negative error code representing the type of error encountered.
Note
The function must create the file and return an open file handle in the fi structure.
Ensure proper handling of file permissions, resource allocation, and any other relevant attributes.
Warning
Verify that the function correctly handles errors and returns the appropriate error codes.
Implement necessary checks to ensure the file is created successfully and is ready for subsequent operations.
Definition at line 1031 of file tcfs.c.
References encrypt_path_and_filename(), encrypt_string(), generate_key(), is_valid_key(), logMessage(), password, prefix_path(), root_path, tcfs_setxattr(), and TCFS_SUCCESS.
tcfs_fsync()
static int tcfs_fsync (const char * fuse_path, int isdatasync, struct fuse_file_info * fi) [static]
Synchronizes file contents.
This function is called to synchronize file contents.
Parameters
fuse_path The path to the file.
datasync Flag indicating whether to sync only data.
fi File information.
Returns
true on success, a negative error code on failure.
Definition at line 1140 of file tcfs.c.
References encrypt_path_and_filename(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_getattr()
static int tcfs_getattr (const char * fuse_path, struct stat * stbuf, struct fuse_file_info * fi) [static]
Gets file attributes.
This function is called to get attributes for a file or directory.
Parameters
fuse_path The path to the file/directory.
stbuf Buffer to fill with attributes.
fi File information.
Returns
TCFS_SUCCESS on success, a negative error code on failure.
Definition at line 99 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_getxattr()
static int tcfs_getxattr (const char * fuse_path, const char * name, char * value, size_t size) [static]
Get extended attribute data.
This function is called to retrieve the value of an extended attribute for a specified file or directory.
Parameters
fuse_path The path of the file or directory within the TCFS.
name The name of the extended attribute.
value Buffer to store the value of the extended attribute.
size The size of the buffer.
Returns
Size of the extended attribute value on success, negative error code on failure.
The getxattr function is invoked to obtain the value of an extended attribute associated with a file or directory within the TCFS file system. The attribute value is stored in the provided buffer (value) with a specified size.
Parameters
fuse_path The path of the file or directory.
name The name of the extended attribute to retrieve.
value Buffer to store the value of the extended attribute.
size The size of the buffer.
Returns
On success, the function returns the size of the extended attribute value. On failure, it returns a negative error code representing the type of error encountered.
Note
The function must ensure that the attribute value is properly retrieved and stored in the provided buffer.
Verify that the correct error codes are returned in case of failures or insufficient buffer size.
Implement appropriate checks to handle different scenarios and edge cases.
Definition at line 1199 of file tcfs.c.
References encrypt_path_and_filename(), logMessage(), password, prefix_path(), and root_path.
Referenced by tcfs_read(), and tcfs_write().
tcfs_link()
static int tcfs_link (const char * from, const char * to) [static]
Creates a hard link.
This function is called to create a hard link.
Parameters
from Source path.
to Target path.
Returns
true on success, a negative error code on failure.
Definition at line 465 of file tcfs.c.
References encrypt_path_and_filename(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_listxattr()
static int tcfs_listxattr (const char * fuse_path, char * list, size_t size) [static]
Lists extended attributes.
This function is called to list extended attributes.
Parameters
fuse_path The path to the file.
list Buffer to fill with the attribute list.
size Size of the buffer.
Returns
Size of the attribute list on success, a negative error code on failure.
Definition at line 1229 of file tcfs.c.
References encrypt_path_and_filename(), logMessage(), password, prefix_path(), and root_path.
tcfs_mkdir()
static int tcfs_mkdir (const char * fuse_path, mode_t mode) [static]
Creates a directory.
This function is called to create a directory.
Parameters
fuse_path The path to the directory.
mode Directory mode.
Returns
true on success, a negative error code on failure.
Definition at line 324 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_mknod()
static int tcfs_mknod (const char * fuse_path, mode_t mode, dev_t rdev) [static]
Creates a regular file or a special file (block or character).
This function is called to create a regular file or a special file.
Parameters
fuse_path The path to the file.
mode File mode.
rdev Device numbers (if the file is a special file).
Returns
true on success, a negative error code on failure.
Definition at line 286 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_open()
static int tcfs_open (const char * fuse_path, struct fuse_file_info * fi) [static]
Opens a file.
This function is called to open a file.
Parameters
fuse_path The path to the file.
fi File information.
Returns
true on success, a negative error code on failure.
Definition at line 651 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_opendir()
static int tcfs_opendir (const char * fuse_path, struct fuse_file_info * fi) [static]
Opens a directory.
This function is called when a directory is opened.
Parameters
fuse_path The path to the directory.
fi File information.
Returns
TCFS_SUCCESS on success, a negative error code on failure.
Definition at line 67 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_read()
static int tcfs_read (const char * fuse_path, char * buf, size_t size, off_t offset, struct fuse_file_info * fi) [static]
Reads data from an open file.
This function is called to read data from an open file.
Parameters
fuse_path The path to the file.
buf Buffer to fill with data.
size Number of bytes to read.
offset Offset within the file.
fi File information.
Returns
The number of bytes read, or a negative error code on failure.
Definition at line 734 of file tcfs.c.
References DECRYPT, decrypt_string(), do_crypt(), encrypt_path(), file_size(), get_user_name(), logMessage(), password, prefix_path(), root_path, and tcfs_getxattr().
tcfs_readdir()
static int tcfs_readdir (const char * fuse_path, void * buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info * fi, enum fuse_readdir_flags frdf) [static]
Reads a directory.
This function is called to read the contents of a directory.
Parameters
fuse_path The path to the directory.
buf Buffer to fill with directory entries.
filler Callback function to add entries to the buffer.
offset The offset within the directory.
fi File information.
frdf Additional flags for readdir operation.
Returns
true on success, a negative error code on failure.
Definition at line 196 of file tcfs.c.
References decrypt_file_name_with_hex(), decrypt_path(), encrypt_path(), ERR_invalid_enc_dir_name, logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_readlink()
static int tcfs_readlink (const char * fuse_path, char * buf, size_t size) [static]
Reads the target of a symbolic link.
This function is called to read the target of a symbolic link.
Parameters
fuse_path The path to the symbolic link.
buf Buffer to fill with the link target.
size The size of the buffer.
Returns
true on success, a negative error code on failure.
Definition at line 162 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_release()
static int tcfs_release (const char * fuse_path, struct fuse_file_info * fi) [static]
Releases an open file.
This function is called to release an open file.
Parameters
fuse_path The path to the file.
fi File information.
Returns
true on success, a negative error code on failure.
Definition at line 1111 of file tcfs.c.
References encrypt_path_and_filename(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_removexattr()
static int tcfs_removexattr (const char * fuse_path, const char * name) [static]
Remove an extended attribute.
This function is called to remove an extended attribute for a specified file or directory.
Parameters
fuse_path The path of the file or directory within the TCFS.
name The name of the extended attribute to remove.
Returns
TCFS_SUCCESS on success, negative error code on failure.
The removexattr function is invoked to remove the specified extended attribute associated with a file or directory within the TCFS file system.
Parameters
fuse_path The path of the file or directory.
name The name of the extended attribute to remove.
Returns
On success, the function returns TCFS_SUCCESS. On failure, it returns a negative error code representing the type of error encountered.
Note
The function must ensure the proper removal of the specified extended attribute.
Verify that the correct error codes are returned in case of failures.
Implement appropriate checks to handle different scenarios and edge cases.
Definition at line 1273 of file tcfs.c.
References encrypt_path_and_filename(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_rename()
static int tcfs_rename (const char * from, const char * to, unsigned int flags) [static]
Renames a file or a directory.
This function is called to rename a file or a directory.
Parameters
from Source path.
to Target path.
flags Flags for the rename operation.
Returns
true on success, a negative error code on failure.
Definition at line 436 of file tcfs.c.
References encrypt_path_and_filename(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_rmdir()
static int tcfs_rmdir (const char * fuse_path) [static]
Removes a directory.
This function is called to remove a directory.
Parameters
fuse_path The path to the directory.
Returns
true on success, a negative error code on failure.
Definition at line 377 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_setxattr()
static int tcfs_setxattr (const char * fuse_path, const char * name, const char * value, size_t size, int flags) [static]
Sets extended attributes.
This function is called to set extended attributes.
Parameters
fuse_path The path to the file.
name Attribute name.
value Attribute value.
size Size of the value.
flags Flags for the setxattr operation.
Returns
true on success, a negative error code on failure.
Definition at line 979 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
Referenced by tcfs_create().
tcfs_statfs()
static int tcfs_statfs (const char * fuse_path, struct statvfs * stbuf) [static]
Get file system statistics.
This function is called when the statfs operation is performed to obtain statistics about the TCFS file system.
Parameters
fuse_path The path of the file system for which statistics are requested.
stbuf Buffer to store file system statistics.
Returns
TCFS_SUCCESS on success, negative error code on failure.
The tcfs_statfs function is invoked to retrieve statistics about the TCFS file system. It may include information such as the total size, free space, and available space.
Parameters
fuse_path The path of the file system within the TCFS.
stbuf Buffer to store the file system statistics.
Returns
true on success. On failure, it returns a negative error code representing the type of error encountered.
Note
The function is essential for providing information about the overall status of the TCFS file system.
Ensure that the file system statistics are accurately retrieved and reported in the stbuf buffer.
Warning
Verify that the function correctly handles errors and returns the appropriate error codes.
The accuracy of the reported statistics is crucial for applications that rely on file system information.
Definition at line 952 of file tcfs.c.
References logMessage(), prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_symlink()
static int tcfs_symlink (const char * from, const char * to) [static]
Creates a symbolic link.
This function is called to create a symbolic link.
Parameters
from Source path of the symbolic link.
to Target path of the symbolic link.
Returns
true on success, a negative error code on failure.
Definition at line 404 of file tcfs.c.
References encrypt_path_and_filename(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_truncate()
static int tcfs_truncate (const char * fuse_path, off_t size, struct fuse_file_info * fi) [static]
Truncates or extends the size of a file.
This function is called to truncate or extend the size of a file.
Parameters
fuse_path The path to the file.
size New size of the file.
fi File information.
Returns
true on success, a negative error code on failure.
Definition at line 559 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_unlink()
static int tcfs_unlink (const char * fuse_path) [static]
Removes a file.
This function is called to remove a file.
Parameters
fuse_path The path to the file.
Returns
true on success, a negative error code on failure.
Definition at line 351 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_utimens()
static int tcfs_utimens (const char * fuse_path, const struct timespec ts[2], struct fuse_file_info * fi) [static]
Modify the access and modification timestamps of a file in the TCFS file system.
This function is called when the utimens operation is performed on a file in the TCFS.
Parameters
fuse_path The path of the encrypted file for which timestamps need to be modified.
ts An array of two timespec structures containing the new access and modification timestamps.
fi File information structure provided by FUSE.
Returns
TCFS_SUCCESS on success, negative error code on failure.
The tcfs_utimens function is invoked to modify the access and modification timestamps of a file within the TCFS. It decodes the encrypted file path, translates it into the actual file path on the underlying file system, and then uses the utimes function to apply the changes to the file timestamps.
Parameters
fuse_path The path of the encrypted file within the TCFS.
ts An array containing two timespec structures. The first structure represents the new access timestamp, and the second represents the new modification timestamp.
fi File information provided by FUSE, which may be used to obtain additional details about the file if needed.
Returns
true on success. On failure, it returns a negative error code representing the type of error encountered.
Definition at line 612 of file tcfs.c.
References encrypt_path(), logMessage(), password, prefix_path(), root_path, and TCFS_SUCCESS.
tcfs_write()
static int tcfs_write (const char * fuse_path, const char * buf, size_t size, off_t offset, struct fuse_file_info * fi) [static]
Writes data to an open file.
This function is called to write data to an open file.
Parameters
fuse_path The path to the file.
buf Data to write.
size Number of bytes to write.
offset Offset within the file.
fi File information.
Returns
The number of bytes written, or a negative error code on failure.
Definition at line 830 of file tcfs.c.
References DECRYPT, decrypt_string(), do_crypt(), ENCRYPT, encrypt_path(), file_size(), logMessage(), password, prefix_path(), root_path, tcfs_access(), tcfs_getxattr(), and TCFS_SUCCESS.
Variable Documentation
argp
struct argp argp = { options, parse_opt, args_doc, doc, 0, NULL, NULL } [static]
TCFS argp structure.
Definition at line 1401 of file tcfs.c.
argp_program_bug_address
const char* argp_program_bug_address = "carloalbertogiordano@duck.com"
TCFS bug report email address.
Definition at line 1332 of file tcfs.c.
argp_program_version
const char* argp_program_version = "TCFS Alpha"
TCFS version information.
Definition at line 1327 of file tcfs.c.
args_doc
char args_doc[] = "" [static]
Argument documentation string for TCFS.
Definition at line 1343 of file tcfs.c.
doc
char doc[] [static]
Initial value:
= "This is an implementation on TCFS\ntcfs -s <source_path> "
                    "-d <dest_path> -p <password> [fuse arguments]"
Documentation string for TCFS.
Definition at line 1337 of file tcfs.c.
options
struct argp_option options[] [static]
Initial value:
= { { "source", 's', "SOURCE", 0, "Source file path", -1 },
        { "destination", 'd', "DESTINATION", 0, "Destination file path", -1 },
        { "password", 'p', "PASSWORD", 0, "Password", -1 },
        { NULL } }
TCFS command-line options.
Definition at line 1348 of file tcfs.c.
password
password
Contains the password passed to TCFS when started.
Definition at line 52 of file tcfs.c.
Referenced by main(), tcfs_access(), tcfs_chmod(), tcfs_chown(), tcfs_create(), tcfs_fsync(), tcfs_getattr(), tcfs_getxattr(), tcfs_link(), tcfs_listxattr(), tcfs_mkdir(), tcfs_mknod(), tcfs_open(), tcfs_opendir(), tcfs_read(), tcfs_readdir(), tcfs_readlink(), tcfs_release(), tcfs_removexattr(), tcfs_rename(), tcfs_rmdir(), tcfs_setxattr(), tcfs_symlink(), tcfs_truncate(), tcfs_unlink(), tcfs_utimens(), and tcfs_write().
root_path
root_path
Contains the fullpath to the mounted directory.
Definition at line 47 of file tcfs.c.
Referenced by main(), tcfs_access(), tcfs_chmod(), tcfs_chown(), tcfs_create(), tcfs_fsync(), tcfs_getattr(), tcfs_getxattr(), tcfs_link(), tcfs_listxattr(), tcfs_mkdir(), tcfs_mknod(), tcfs_open(), tcfs_opendir(), tcfs_read(), tcfs_readdir(), tcfs_readlink(), tcfs_release(), tcfs_removexattr(), tcfs_rename(), tcfs_rmdir(), tcfs_setxattr(), tcfs_statfs(), tcfs_symlink(), tcfs_truncate(), tcfs_unlink(), tcfs_utimens(), and tcfs_write().
tcfs_oper
struct fuse_operations tcfs_oper [static]
Initial value:
= {
  .opendir = tcfs_opendir,
  .getattr = tcfs_getattr,
  .access = tcfs_access,
  .readlink = tcfs_readlink,
  .readdir = tcfs_readdir,
  .mknod = tcfs_mknod,
  .mkdir = tcfs_mkdir,
  .symlink = tcfs_symlink,
  .unlink = tcfs_unlink,
  .rmdir = tcfs_rmdir,
  .rename = tcfs_rename,
  .link = tcfs_link,
  .chmod = tcfs_chmod,
  .chown = tcfs_chown,
  .truncate = tcfs_truncate,
  .utimens = tcfs_utimens,
  .open = tcfs_open,
  .read = tcfs_read,
  .write = tcfs_write,
  .statfs = tcfs_statfs,
  .create = tcfs_create,
  .release = tcfs_release,
  .fsync = tcfs_fsync,
  .setxattr = tcfs_setxattr,
  .getxattr = tcfs_getxattr,
  .listxattr = tcfs_listxattr,
  .removexattr = tcfs_removexattr,
}
TCFS file system operations.
This structure defines the operations supported by the TCFS file system.
Definition at line 1294 of file tcfs.c.
Referenced by main().