daemon/daemon_utils/common_utils/db/user_db.c File Reference
This file contains the functions to interact with the database.
#include "user_db.h"
#include "redis.h"
Functions
int register_user (qm_user *user_msg)
Register or update a user in the db, this relies on the redis.c file.
int unregister_user (pid_t pid)
Remove a user from the DB.
void disconnect_db (void)
Free the context of the DB.
Detailed Description
This file contains the functions to interact with the database.
Definition in file user_db.c.
Function Documentation
disconnect_db()
void disconnect_db (void)
Free the context of the DB.
Parameters
void
Returns
void
Note
If this fails no errors will be printed and no errno will be set, you are on your own :(
Definition at line 45 of file user_db.c.
References free_context(), and print_msg().
register_user()
int register_user (qm_user * user_msg)
Register or update a user in the db, this relies on the redis.c file.
Parameters
qm_user* A pointer to the allocated qm_user* struct
Returns
1 if successful, 0 otherwise. An error might be printen by print_err() function,
See also
print_err
Definition at line 15 of file user_db.c.
References init_context(), insert(), print_all_keys(), and print_msg().
unregister_user()
int unregister_user (pid_t pid)
Remove a user from the DB.
Parameters
pid_t pid the key
Returns
1 if successful, 0 otherwise. An error might be printen by print_err() function,
See also
print_err
Definition at line 31 of file user_db.c.
References print_all_keys(), print_msg(), and remove_by_pid().