.TH "ServerREST Directory Reference" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerREST Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcrypt\-utils\fP"
.br
.ti -1c
.RI "directory \fBdb\fP"
.br
.ti -1c
.RI "directory \fBserverTools\fP"
.br
.ti -1c
.RI "directory \fBtypes\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain_test\&.go\fP"
.br
.ti -1c
.RI "file \fBtcfs\-daemon\&.go\fP"
.br
.in -1c
