.TH "user/old_stuff Directory Reference" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user/old_stuff Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtcfs_helper_tools\&.c\fP"
.br
.RI "This file contains the logic and implementation of functions needed to perform the operations requested in \fBuser_tcfs\&.c\fP\&. "
.ti -1c
.RI "file \fBtcfs_helper_tools\&.h\fP"
.br
.ti -1c
.RI "file \fBuser_tcfs\&.c\fP"
.br
.RI "Help the user that wants to use TCFS\&. "
.in -1c
