.TH "kernel-module Directory Reference" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel-module Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtcfs_kmodule\&.c\fP"
.br
.RI "This will host the kernel module implementation in the future\&. It is not beeing currently developed\&. "
.in -1c
