.TH "arguments" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arguments \- Structure to store command-line arguments\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBoperation\fP"
.br
.RI "Decribes the operation that will be executed by the main function\&. "
.ti -1c
.RI "char * \fBsource\fP"
.br
.ti -1c
.RI "char * \fBdestination\fP"
.br
.ti -1c
.RI "char * \fBpassword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure to store command-line arguments\&. 

Structure to hold the parsed arguments\&. 
.PP
Definition at line \fB48\fP of file \fBuser_tcfs\&.c\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char* arguments::destination"

.PP
Definition at line \fB1360\fP of file \fBtcfs\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, and \fBparse_opt()\fP\&.
.SS "int arguments::operation"

.PP
Decribes the operation that will be executed by the main function\&. 
.PP
Definition at line \fB50\fP of file \fBuser_tcfs\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, and \fBparse_opt()\fP\&.
.SS "char* arguments::password"

.PP
Definition at line \fB1361\fP of file \fBtcfs\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, and \fBparse_opt()\fP\&.
.SS "char* arguments::source"

.PP
Definition at line \fB1359\fP of file \fBtcfs\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, and \fBparse_opt()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
