.TH "command_handler.enviroinment" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command_handler.enviroinment
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcountdown\fP (msg, delta)"
.br
.ti -1c
.RI "\fBinit_env\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "command_handler\&.enviroinment\&.countdown ( msg,  delta)"

.PP
Definition at line \fB6\fP of file \fBenviroinment\&.py\fP\&.
.PP
Referenced by \fBcommand_handler\&.enviroinment\&.init_env()\fP\&.
.SS "command_handler\&.enviroinment\&.init_env ()"

.PP
Definition at line \fB12\fP of file \fBenviroinment\&.py\fP\&.
.PP
References \fBcommand_handler\&.enviroinment\&.countdown()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
