.TH "deprecated" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.PP

.IP "\fBMember \fBget_encrypted_key\fP (char *filepath, unsigned char *encrypted_key)\fP" 1c
Currently has no use\&. Was once used for debugging\&.  
.IP "\fBMember \fBprint_aes_key\fP (unsigned char *key)\fP" 1c
Currently has no use\&. Printing the AES key is considered excessive\&.  
.IP "\fBMember \fBread_file\fP (FILE *file)\fP" 1c
Currently has no use\&. 
.PP

