.TH "user/command_handler/enviroinment.py" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user/command_handler/enviroinment.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcommand_handler\fP"
.br
.ti -1c
.RI "namespace \fBcommand_handler\&.enviroinment\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcommand_handler\&.enviroinment\&.countdown\fP (msg, delta)"
.br
.ti -1c
.RI "\fBcommand_handler\&.enviroinment\&.init_env\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
