.TH "user/main.py" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user/main.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmain\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\&.foo\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmain\&.win\fP = \fBWindow\fP('TCFS user helper', '200x200')"
.br
.ti -1c
.RI "\fBmain\&.init_env_butt\fP = win\&.add_button('Initialize the environment', \fBfoo\fP, row=0, col=0)"
.br
.ti -1c
.RI "\fBmain\&.mount_butt\fP = win\&.add_button('Mount TCFS', \fBfoo\fP, row=1, col=0)"
.br
.ti -1c
.RI "\fBmain\&.umount_butt\fP = win\&.add_button('Umount TCFS', \fBfoo\fP, row=2, col=0)"
.br
.ti -1c
.RI "\fBmain\&.shared_butt\fP = win\&.add_button('Threshold share', \fBfoo\fP, row=3, col=0)"
.br
.ti -1c
.RI "\fBmain\&.logout_butt\fP = win\&.add_button('Logout', \fBfoo\fP, row=4, col=0)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
