.TH "user/ui/main_window.py" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user/ui/main_window.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBui\&.main_window\&.Window\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBui\fP"
.br
.ti -1c
.RI "namespace \fBui\&.main_window\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBui\&.main_window\&.modify_button_allign\fP (button, row, column)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
