.TH "main" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfoo\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBwin\fP = \fBWindow\fP('TCFS user helper', '200x200')"
.br
.ti -1c
.RI "\fBinit_env_butt\fP = win\&.add_button('Initialize the environment', \fBfoo\fP, row=0, col=0)"
.br
.ti -1c
.RI "\fBmount_butt\fP = win\&.add_button('Mount TCFS', \fBfoo\fP, row=1, col=0)"
.br
.ti -1c
.RI "\fBumount_butt\fP = win\&.add_button('Umount TCFS', \fBfoo\fP, row=2, col=0)"
.br
.ti -1c
.RI "\fBshared_butt\fP = win\&.add_button('Threshold share', \fBfoo\fP, row=3, col=0)"
.br
.ti -1c
.RI "\fBlogout_butt\fP = win\&.add_button('Logout', \fBfoo\fP, row=4, col=0)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "main\&.foo ()"

.PP
Definition at line \fB4\fP of file \fBmain\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "main\&.init_env_butt = win\&.add_button('Initialize the environment', \fBfoo\fP, row=0, col=0)"

.PP
Definition at line \fB10\fP of file \fBmain\&.py\fP\&.
.SS "main\&.logout_butt = win\&.add_button('Logout', \fBfoo\fP, row=4, col=0)"

.PP
Definition at line \fB14\fP of file \fBmain\&.py\fP\&.
.SS "main\&.mount_butt = win\&.add_button('Mount TCFS', \fBfoo\fP, row=1, col=0)"

.PP
Definition at line \fB11\fP of file \fBmain\&.py\fP\&.
.SS "main\&.shared_butt = win\&.add_button('Threshold share', \fBfoo\fP, row=3, col=0)"

.PP
Definition at line \fB13\fP of file \fBmain\&.py\fP\&.
.SS "main\&.umount_butt = win\&.add_button('Umount TCFS', \fBfoo\fP, row=2, col=0)"

.PP
Definition at line \fB12\fP of file \fBmain\&.py\fP\&.
.SS "main\&.win = \fBWindow\fP('TCFS user helper', '200x200')"

.PP
Definition at line \fB8\fP of file \fBmain\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
