.TH "userspace-module/utils/password_manager/password_manager.c" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
userspace-module/utils/password_manager/password_manager.c \- This file will handle key exchanges with the kernel module\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This file will handle key exchanges with the kernel module\&. 

This is not being currently developed 
.PP
Definition in file \fBpassword_manager\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
