.TH "userspace-module/utils/password_manager/password_manager.h" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
userspace-module/utils/password_manager/password_manager.h
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWITH_SYS_CALL\fP   1"
.br
.RI "the system aims to be independent from the kernel module\&. The kernel module is not beeing developed so this is useless\&. This definition is marked as internal and should not be used directly by the user "
.ti -1c
.RI "#define \fBWITHOUT_SYS_CALL\fP   0"
.br
.RI "the system aims to be independent from the kernel module\&. The kernel module is not beeing developed so this is useless\&. This definition is marked as internal and should not be used directly by the user "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define WITH_SYS_CALL   1"

.PP
the system aims to be independent from the kernel module\&. The kernel module is not beeing developed so this is useless\&. This definition is marked as internal and should not be used directly by the user 
.PP
Definition at line \fB10\fP of file \fBpassword_manager\&.h\fP\&.
.SS "#define WITHOUT_SYS_CALL   0"

.PP
the system aims to be independent from the kernel module\&. The kernel module is not beeing developed so this is useless\&. This definition is marked as internal and should not be used directly by the user 
.PP
Definition at line \fB17\fP of file \fBpassword_manager\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
