.TH "qm_broad" 3 "Tue Nov 28 2023 12:06:42" "Version 0.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qm_broad \- Represents a broadcast message\&. Contains the data that is broadcasted to all users\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a broadcast message\&. Contains the data that is broadcasted to all users\&. 
.PP
Definition at line \fB81\fP of file \fBcommon\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char* qm_broad::data"
The data that is broadcasted\&. 
.PP
Definition at line \fB82\fP of file \fBcommon\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
