.TH "qm_shared" 3 "Mon Nov 27 2023 17:03:19" "Version 0.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qm_shared
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "char ** \fBuserlist\fP"
.br
.ti -1c
.RI "char * \fBkeypart\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB34\fP of file \fBcommon\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int qm_shared::fd"

.PP
Definition at line \fB35\fP of file \fBcommon\&.h\fP\&.
.SS "char* qm_shared::keypart"

.PP
Definition at line \fB37\fP of file \fBcommon\&.h\fP\&.
.SS "char** qm_shared::userlist"

.PP
Definition at line \fB36\fP of file \fBcommon\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
