.TH "qm_user" 3 "Tue Nov 28 2023 15:14:43" "Version 0.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qm_user \- Represents a user message\&. 
.br
Contains information about the user's operation, process ID, username and public key\&. 
.br
\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuser_operation\fP \fBuser_op\fP"
.br
.ti -1c
.RI "pid_t \fBpid\fP"
.br
.ti -1c
.RI "char * \fBuser\fP"
.br
.ti -1c
.RI "char * \fBpubkey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a user message\&. 
.br
Contains information about the user's operation, process ID, username and public key\&. 
.br
\&. 
.PP
Definition at line \fB61\fP of file \fBcommon\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pid_t qm_user::pid"
The process ID of the user\&. 
.PP
Definition at line \fB63\fP of file \fBcommon\&.h\fP\&.
.PP
Referenced by \fBget_user_by_name()\fP, \fBget_user_by_pid()\fP, \fBhandle_outgoing_messages()\fP, \fBinsert()\fP, \fBremove_by_user()\fP, \fBstring_to_struct()\fP, and \fBstruct_to_json()\fP\&.
.SS "char* qm_user::pubkey"
The public key of the user\&. 
.PP
Definition at line \fB65\fP of file \fBcommon\&.h\fP\&.
.PP
Referenced by \fBhandle_outgoing_messages()\fP, \fBstring_to_struct()\fP, and \fBstruct_to_json()\fP\&.
.SS "char* qm_user::user"
The username of the user\&. 
.PP
Definition at line \fB64\fP of file \fBcommon\&.h\fP\&.
.PP
Referenced by \fBget_user_by_name()\fP, \fBget_user_by_pid()\fP, \fBhandle_outgoing_messages()\fP, \fBinsert()\fP, \fBremove_by_pid()\fP, \fBstring_to_struct()\fP, and \fBstruct_to_json()\fP\&.
.SS "\fBuser_operation\fP qm_user::user_op"
The operation that the user wants to perform\&. 
.PP
Definition at line \fB62\fP of file \fBcommon\&.h\fP\&.
.PP
Referenced by \fBhandle_outgoing_messages()\fP, \fBstring_to_struct()\fP, and \fBstruct_to_json()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
