.TH "qm_user" 3 "Mon Nov 27 2023 17:03:19" "Version 0.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qm_user
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "user_operation \fBuser_op\fP"
.br
.ti -1c
.RI "pid_t \fBpid\fP"
.br
.ti -1c
.RI "char * \fBuser\fP"
.br
.ti -1c
.RI "char * \fBpubkey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB27\fP of file \fBcommon\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pid_t qm_user::pid"

.PP
Definition at line \fB29\fP of file \fBcommon\&.h\fP\&.
.SS "char* qm_user::pubkey"

.PP
Definition at line \fB31\fP of file \fBcommon\&.h\fP\&.
.SS "char* qm_user::user"

.PP
Definition at line \fB30\fP of file \fBcommon\&.h\fP\&.
.SS "user_operation qm_user::user_op"

.PP
Definition at line \fB28\fP of file \fBcommon\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
