.TH "kernel-module/tcfs_kmodule.c" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel-module/tcfs_kmodule.c \- This will host the kernel module implementation in the future\&. It is not beeing currently developed\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This will host the kernel module implementation in the future\&. It is not beeing currently developed\&. 


.PP
Definition in file \fBtcfs_kmodule\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
