.TH "todo" 3 "Sun Jan 21 2024 18:41:36" "Version 0.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.PP

.IP "\fBMember \fBget_pass\fP (char *pw)\fP" 1c
This will be changed when a public/private key model will be avilable to TCFS userspace module  
.IP "\fBMember \fBtcfs_opendir\fP (const char *fuse_path, struct fuse_file_info *fi)\fP" 1c
Implement the opendir function 
.PP

