.TH "ui.main_window" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui.main_window
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmodify_button_allign\fP (button, row, column)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ui\&.main_window\&.modify_button_allign ( button,  row,  column)"

.PP
Definition at line \fB4\fP of file \fBmain_window\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
