.TH "ui.main_window.Window" 3 "Thu Feb 1 2024 17:25:40" "Version 0.3.2" "TCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui.main_window.Window
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, str title, str geometry)"
.br
.ti -1c
.RI "\fBadd_button\fP (self, str text, function, row=0, col=0)"
.br
.ti -1c
.RI "\fBstart_window\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBwindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBmain_window\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ui\&.main_window\&.Window\&.__init__ ( self, str title, str geometry)"

.PP
Definition at line \fB10\fP of file \fBmain_window\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "ui\&.main_window\&.Window\&.add_button ( self, str text,  function,  row = \fC0\fP,  col = \fC0\fP)"

.PP
Definition at line \fB15\fP of file \fBmain_window\&.py\fP\&.
.PP
References \fBui\&.main_window\&.Window\&.window\fP\&.
.SS "ui\&.main_window\&.Window\&.start_window ( self)"

.PP
Definition at line \fB20\fP of file \fBmain_window\&.py\fP\&.
.PP
References \fBui\&.main_window\&.Window\&.window\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ui\&.main_window\&.Window\&.window"

.PP
Definition at line \fB11\fP of file \fBmain_window\&.py\fP\&.
.PP
Referenced by \fBui\&.main_window\&.Window\&.add_button()\fP, and \fBui\&.main_window\&.Window\&.start_window()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TCFS from the source code\&.
